### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'NoneType'

### ISSUE THREAD

**Issue by allanrgc** [allanrgc/desafio_workshop_backend_2023_2#1]
Acessando a path http://127.0.0.1:8000/carrinho/itens/ e tentar adicionar algum item ao carrinho do usuário selecionado surge o erro apresentado no título. Segue caminho do erro:
File "C:\Users\Adm\Documents\Unipe\Fábrica de Software\desafio_workshop_backend_2023_2\carrinho\models.py", line 51, in save
    self.total = self.produto.valor * self.quantidade
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'NoneType'

Outro erro presente aparece ao tentar abrir o carrinho. Segue a path: http://127.0.0.1:8000/carrinho/carrinhos/

**Comment by pdr-tuche** [comment]
esse erro ai, é por conta de alguns campos novos que estao no serializer que tem como argumento "source"
